FROM python:slim

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .

CMD ["python3", "-m", "app"]