FROM python:slim

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY . .


CMD ["celery", "-A", "workers.1_deploy_ens", "worker", "--loglevel=INFO", "--concurrency=4", "-Q", "queue_app_1", "-n", "worker1"]
