version: "3.7"
services:
  # flask_app:
  #   build: './flask_app'
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - rabbit

  rabbit:
    hostname: rabbit
    container_name: rabbit_queue
    image: "rabbitmq:3.9-management"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    # ports:
    #   - "15672:15672"
    #   - "5672:5672"
    expose:
      - 15672
      - 5672

  daas_worker:
    build: 
      context: "."
      dockerfile: dockerfile
    env_file:
      - .env
    depends_on:
      - rabbit