FROM python:3.9.6

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

WORKDIR /usr/src/app

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN pip install tqdm

# RUN apt-get install -y software-properties-common
# RUN add-apt-repository ppa:ethereum/ethereum
# RUN add-apt-repository ppa:ethereum/ethereum-dev
# RUN apt update
# RUN apt-get install solc

COPY . .